### ISSUE TITLE
Add Support for Translate?

### ISSUE THREAD

**Issue by tonydewan** [zachstronaut/jquery-animate-css-rotate-scale#1]
This is more a feature request than an issue, but do you have plans to add support for other translations?  TranslateX, TranslateY, etc.

**Comment by tonydewan** [comment]
Forked and support (partially) added: tonydewan/jquery-animate-css-rotate-scale@3994603991c877ca8761fc8f56afc6267e12925e

**Comment by tonydewan** [comment]
Lets try this: http://github.com/tonydewan/jquery-animate-css-rotate-scale

**Comment by zachstronaut** [comment]
There's a few people who have forked and added support for all the transform functions.... skew, translate, and the various 3D ones from Safari 5.  I'd consider pulling the right implementation back into my tree, or I may take a stab at it.

**Comment by tonydewan** [comment]
I'm no longer using this anywhere, so I'm probably not going to get to it anytime soon.
