### ISSUE TITLE
returning this

### ISSUE THREAD

**Issue by fflorent** [zachstronaut/jquery-animate-css-rotate-scale#2]
Hi,
why not returning this, in $.fn.rotate and $.fn.scale ? (as suggested in http://docs.jquery.com/Plugins/Authoring )

Indeed, it would let us use your functions like below : 
$("#id").scale(1.5).rotate(60);

**Comment by zachstronaut** [comment]
Thanks for pointing this bug out.  My next push will have a fix for this.
